from assets.lib import *
set_process(0)
fire_the_cannons_func()
fire_the_cannons_func(velocity=20.0)
fire_the_cannons_func(angle=60.0)
fire_the_cannons_func(velocity=15.0,angle=50.0)
reveal_your_plunder_func()
fire_the_cannons_func()
where_be_that_func()
does_i_hit_func(distance=10.0)
reveal_your_plunder_func()
how_do_ye_fire_func(distance=100.0)
ye_fire_that_func()
does_i_hit_func(distance=100.0)
reveal_your_plunder_func()
